using Microsoft.CodeAnalysis;

namespace CodeInvocationGenerationApp;

/// <summary>
/// A sample source generator that creates C# classes based on the text file (in this case, Domain Driven Design ubiquitous language registry).
/// When using a simple text file as a baseline, we can create a non-incremental source generator.
/// </summary>
[Generator]
public class SampleSourceGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // No initialization required for this generator.
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var className = "Invoker";

        // Build up the source code.
        string source = $$"""
                          // <auto-generated/>

                          using CodeInvocationBenchmarkApp.Events;
                          using CodeInvocationBenchmarkApp.Handlers;
                          
                          namespace CodeInvocationGenerationApp
                          {
                              public static class {{className}}
                              {
                                  public static void Invoke(object handler, object @event)
                                  {
                                      ((MyEventHandler)handler).Handle((MyEvent)@event);
                                  }
                              }
                          }

                          """;
        
        context.AddSource($"{className}.g.cs", source);
    }
}
